FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt update && apt install -y curl && apt-get install -y gcc ccache && apt-get install -y libgl1 libglib2.0-0 ffmpeg

COPY requirements.txt ./
RUN pip install --no-cache-dir --prefer-binary -r requirements.txt

RUN pip install paddlepaddle -f https://www.paddlepaddle.org.cn/whl/linux/noavx/stable.html

COPY . .

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]