name: Deploy to Local

on:
  push:
    branches:
      - main

jobs:
  deploy_to_local:
    runs-on: [dgx-2]

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
    
      - name: Build Docker image
        run: |
          docker build -t pdf_extractor_llm:dev -f Dockerfile.dev .
    
      - name: Deploy to Docker Swarm
        run: |
          # Remove the service if it exists (optional)
          docker service rm pdf_extractor_llm || true

          # Create the service with 3 replicas, GPU support, and env vars
          docker service create \
            --name pdf_extractor_llm \
            --replicas 3 \
            --publish published=8002,target=8000 \
            --env OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
            --env OLLAMA_BASE_URL="${{ secrets.OLLAMA_BASE_URL }}" \
            --env EMBEDDING_MODEL="${{ secrets.EMBEDDING_MODEL }}" \
            --env LLM_MODEL="${{ secrets.LLM_MODEL }}" \
            --env NVIDIA_VISIBLE_DEVICES=all \
            --constraint 'node.labels.gpu == true' \
            pdf_extractor_llm:dev

    environment:
      name: dev_environment
